from django.urls import path, reverse_lazy

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

from soccer.views import (
     views,
     player_views,
     manager_views,
     club_views,
     national_views,
)

app_name = 'soccer'
urlpatterns = [
     path('', views.IndexView.as_view(), name='index'),

     path('player/', player_views.PlayerIndexView.as_view(), name='player_index'),
     path('player/list/', player_views.PlayerListView.as_view(), name='player_list'),
     path('player/list/comment-count/', player_views.PlayerListCommentCountView.as_view(), name='player_list_comment_count'),
     path('player/list/average-rating/', player_views.PlayerListAvgRatingView.as_view(), name='player_list_avg_rating'),
     path('player/<int:pk>/', player_views.PlayerDetailView.as_view(), name='player_detail'),
     path('player/<int:pk>/like-count/', player_views.PlayerDetailLikeCountView.as_view(), name='player_detail_like_count'),
     path('player/<int:pk>/high-rating/', player_views.PlayerDetailHighRatingView.as_view(), name='player_detail_high_rating'),
     path('player/<int:pk>/low-rating/', player_views.PlayerDetailLowRatingView.as_view(), name='player_detail_low_rating'),

     path('player/position/', player_views.PlayerPositionListView.as_view(), name='player_position_list'),
     path('player/position/<str:position_name>/', player_views.PositionPlayerListView.as_view(), name='position_player_list'),
     path('player/position/<str:position_name>/comment-count/', player_views.PositionPlayerListCommentCountView.as_view(), name='position_player_list_comment_count'),
     path('player/position/<str:position_name>/average-rating/', player_views.PositionPlayerListAvgRatingView.as_view(), name='position_player_list_avg_rating'),

     path('player/league/', player_views.PlayerLeagueListView.as_view(), name='player_league_list'),
     path('player/league/<str:player_league_slug>/',
          player_views.PlayerLeagueTeamView.as_view(), name='player_league_team'),
     path('team/<str:player_team_slug>/players/',
          player_views.TeamPlayerListView.as_view(), name='team_player_list'),
     path('team/<str:player_team_slug>/players/comment-count/',
          player_views.TeamPlayerListCommentCountView.as_view(), name='team_player_list_comment_count'),
     path('team/<str:player_team_slug>/players/average-rating/',
          player_views.TeamPlayerListAvgRatingView.as_view(), name='team_player_list_avg_rating'),
     path('team/<str:player_team_slug>/players/position/',
          player_views.TeamPositionListView.as_view(), name='team_position_list'),
     path('team/<str:player_team_slug>/players/position/<str:position_name>/',
          player_views.TeamPlayerListPositionView.as_view(), name='team_player_list_position'),
     path('team/<str:player_team_slug>/players/position/<str:position_name>/comment-count/',
          player_views.TeamPlayerListPositionCommentCountView.as_view(), name='team_player_list_position_comment_count'),
     path('team/<str:player_team_slug>/players/position/<str:position_name>/average-rating/',
          player_views.TeamPlayerListPositionAvgRatingView.as_view(), name='team_player_list_position_avg_rating'),
          
     path('player/area/', player_views.PlayerAreaListView.as_view(), name='player_area_list'),
     path('player/area/<str:player_area_slug>/',
          player_views.PlayerAreaCountryView.as_view(), name='player_area_country'),
     path('country/<str:player_country_slug>/players/',
          player_views.CountryPlayerListView.as_view(), name='country_player_list'),
     path('country/<str:player_country_slug>/players/comment-count/',
          player_views.CountryPlayerListCommentCountView.as_view(), name='country_player_list_comment_count'),
     path('country/<str:player_country_slug>/players/average-rating/',
          player_views.CountryPlayerListAvgRatingView.as_view(), name='country_player_list_avg_rating'),
     path('country/<str:player_country_slug>/players/position/',
          player_views.CountryPositionListView.as_view(), name='country_position_list'),
     path('country/<str:player_country_slug>/players/position/<str:position_name>/',
          player_views.CountryPlayerListPositionView.as_view(), name='country_player_list_position'),
     path('country/<str:player_country_slug>/players/position/<str:position_name>/comment-count/',
          player_views.CountryPlayerListPositionCommentCountView.as_view(), name='country_player_list_position_comment_count'),
     path('country/<str:player_country_slug>/players/position/<str:position_name>/average-rating/',
          player_views.CountryPlayerListPositionAvgRatingView.as_view(), name='country_player_list_position_avg_rating'),

     path('player/search/', player_views.SearchPlayerView.as_view(), name='search_player'),

     path('player/comment/list/', player_views.CommnetListView.as_view(), name='player_comment_list'),
     path('player/comment/list/like-count/', player_views.CommnetListLikeCountView.as_view(), name='player_comment_list_like_count'),
     path('player/comment/list/high-rating/', player_views.CommnetListHighRatingView.as_view(), name='player_comment_list_high_rating'),
     path('player/comment/list/low-rating/', player_views.CommnetListLowRatingView.as_view(), name='player_comment_list_low_rating'),
     path('player/comment/<int:pk>/', player_views.CommentFormView.as_view(), name='comment_form'),    
     path('player/comment/<int:pk>/remove/', player_views.comment_remove, name='comment_remove'),
     path('player/like/<int:pk>/', player_views.player_like, name='player_like'),
     
     path('manager/', manager_views.ManagerIndexView.as_view(), name='manager_index'),

     path('manager/area/', manager_views.ManagerAreaView.as_view(), name='manager_area_list'),
     path('manager/area/<str:area_slug>/', manager_views.ManagerAreaCountryView.as_view(), name='manager_area_country'),
     path('country/<str:manager_country_slug>/managers/', manager_views.CountryManagerView.as_view(), name='country_manager_list'),
     path('country/<str:manager_country_slug>/managers/comment-count/', manager_views.CountryManagerCommentCountView.as_view(), name='country_manager_list_comment_count'),
     path('country/<str:manager_country_slug>/managers/avg-rating/', manager_views.CountryManagerAvgRatingView.as_view(), name='country_manager_list_avg_rating'),
     path('manager/league/', manager_views.ManagerLeagueListView.as_view(), name='manager_league_list'),
     path('manager/league/<str:manager_league_slug>/', manager_views.ManagerLeagueTeamView.as_view(), name='manager_league_team'),
     path('<str:manager_team_slug>/manager/', manager_views.TeamManagerView.as_view(), name='team_manager_list'),
     path('<str:manager_team_slug>/manager/comment-count/', manager_views.TeamManagerCommentCountView.as_view(), name='team_manager_list_comment_count'),
     path('<str:manager_team_slug>/manager/avg_rating/', manager_views.TeamManagerAvgRatingView.as_view(), name='team_manager_list_avg_rating'),
     
     path('manager/list/', manager_views.ManagerListView.as_view(), name='manager_list'),
     path('manager/list/comment-count/', manager_views.ManagerListCommentCountView.as_view(), name='manager_list_comment_count'),
     path('manager/list/avg-rating/', manager_views.ManagerListAvgRatingView.as_view(), name='manager_list_avg_rating'),
     path('manager/<int:pk>/', manager_views.ManagerDetailView.as_view(), name='manager_detail'),
     path('manager/<int:pk>/like-count/', manager_views.ManagerDetailLikeCountView.as_view(), name='manager_detail_like_count'),
     path('manager/<int:pk>/high-rating/', manager_views.ManagerDetailHighRatingView.as_view(), name='manager_detail_high_rating'),
     path('manager/<int:pk>/low-rating/', manager_views.ManagerDetailLowRatingView.as_view(), name='manager_detail_low_rating'),
     path('manager/comment/list/', manager_views.ManagerCommnetListView.as_view(), name='manager_comment_list'),
     path('manager/comment/list/like-count/', manager_views.ManagerCommnetListLikeCountView.as_view(), name='manager_comment_list_like_count'),
     path('manager/comment/list/high-rating/', manager_views.ManagerCommnetListHighRatingView.as_view(), name='manager_comment_list_high_rating'),
     path('manager/comment/list/low-rating/', manager_views.ManagerCommnetListLowRatingView.as_view(), name='manager_comment_list_low_rating'),
     path('manager/comment/<int:pk>/', manager_views.ManagerCommentFormView.as_view(), name='manager_comment_form'),
     path('manager/comment/<int:pk>/remove/', manager_views.manager_comment_remove, name='manager_comment_remove'),
     path('manager/like/<int:pk>/', manager_views.manager_like, name='manager_like'),
     path('manager/search/', manager_views.SearchManagerView.as_view(), name='search_manager'),

     path('team/', club_views.ClubIndexView.as_view(), name='club_index'),
     path('league/', club_views.LeagueItemListView.as_view(), name='league_item_list'),
     path('league/<str:league_slug>/', club_views.LeagueClubView.as_view(), name='league_club'),
     path('league/<str:league_slug>/comment-count/', club_views.LeagueClubCommentCountView.as_view(), name='league_club_comment_count'),
     path('league/<str:league_slug>/average-rating/', club_views.LeagueClubAvgRatingView.as_view(), name='league_club_avg_rating'),
     path('team/<slug>/', club_views.ClubDetailView.as_view(), name='club_detail'),
     path('team/<slug>/like-count/', club_views.ClubDetailLikeCountView.as_view(), name='club_detail_like_count'),
     path('team/<slug>/high-rating/', club_views.ClubDetailHighRatingView.as_view(), name='club_detail_high_rating'),
     path('team/<slug>/low-rating/', club_views.ClubDetailLowRatingView.as_view(), name='club_detail_low_rating'),
     path('team/<slug>/comment/', club_views.ClubCommentFormView.as_view(), name='club_comment_form'),
     path('team/comment/<int:pk>/remove/', club_views.club_comment_remove, name='club_comment_remove'),
     path('team/like/<int:pk>/', club_views.club_like, name='club_like'),
     path('team/comment/list/', club_views.ClubCommnetListView.as_view(), name='club_comment_list'),
     path('team/comment/list/like-count/', club_views.ClubCommnetListLikeCountView.as_view(), name='club_comment_list_like_count'),
     path('team/comment/list/high-rating/', club_views.ClubCommnetListHighRatingView.as_view(), name='club_comment_list_high_rating'),
     path('team/comment/list/low-rating/', club_views.ClubCommnetListLowRatingView.as_view(), name='club_comment_list_low_rating'),
     path('club-team/search/', club_views.SearchClubView.as_view(), name='search_club'),

     path('country/', national_views.NationalIndexView.as_view(), name='national_index'),
     path('area/', national_views.AreaItemListView.as_view(), name='area_item_list'),
     path('area/<str:area_slug>/', national_views.AreaNationalView.as_view(), name='area_national'),
     path('area/<str:area_slug>/comment-count/', national_views.AreaNationalCommentCountView.as_view(), name='area_national_comment_count'),
     path('area/<str:area_slug>/average-rating/', national_views.AreaNationalAvgRatingView.as_view(), name='area_national_avg_rating'),
     path('country/<slug>/',
          national_views.NationalDetailView.as_view(), name='national_detail'),
     path('country/<slug>/like-count/',
          national_views.NationalDetailLikeCountView.as_view(), name='national_detail_like_count'),
     path('country/<slug>/high-rating/',
          national_views.NationalDetailHighRatingView.as_view(), name='national_detail_high_rating'),
     path('country/<slug>/low-rating/',
          national_views.NationalDetailLowRatingView.as_view(), name='national_detail_low_rating'),
     path('country/<slug>/comment/', national_views.NationalCommentFormView.as_view(), name='national_comment_form'),
     path('country/comment/<int:pk>/remove/', national_views.national_comment_remove, name='national_comment_remove'),
     path('country/like/<int:pk>/', national_views.national_like, name='national_like'),
     path('country/comment/list/', national_views.NationalCommnetListView.as_view(), name='national_comment_list'),
     path('country/comment/list/like-count/', national_views.NationalCommnetListLikeCountView.as_view(), name='national_comment_list_like_count'),
     path('country/comment/list/high-rating/', national_views.NationalCommnetListHighRatingView.as_view(), name='national_comment_list_high_rating'),
     path('country/comment/list/low-rating/', national_views.NationalCommnetListLowRatingView.as_view(), name='national_comment_list_low_rating'),
     path('national-team/search/', national_views.SearchNationalView.as_view(), name='search_national'),

     path('request/', views.RequestFormView.as_view(), name='request_form'),
     path('request-manager/', manager_views.ManagerNewCreateRequestFormView.as_view(), name='manager_new_create_request_form'),
     path('request-player/', player_views.PlayerNewCreateRequestFormView.as_view(), name='player_new_create_request_form'),
     path('request-team/', club_views.ClubNewCreateRequestFormView.as_view(), name='club_team_new_create_request_form'),
     path('request-country/', national_views.NationalNewCreateRequestFormView.as_view(), name='national_team_new_create_request_form'),
     path('request/manager/result/', views.RequestResultView.as_view(), name='manager_request_result'),
     path('request/player/result/', views.RequestResultView.as_view(), name='player_request_result'),
     path('request/team/result/', views.RequestResultView.as_view(), name='club_team_request_result'),
     path('request/country/result/', views.RequestResultView.as_view(), name='national_team_request_result'),
     path('player/<int:pk>/update/request/', player_views.PlayerUpdateRequestFormView.as_view(), name='player_update_request_form'),
     path('manager/<int:pk>/update/request/', manager_views.ManagerUpdateRequestFormView.as_view(), name='manager_update_request_form'),
     path('team/<slug>/update/request/', club_views.ClubUpdateRequestFormView.as_view(), name='club_team_update_request_form'),
     path('country/<slug>/update/request/', national_views.NationalUpdateRequestFormView.as_view(), name='national_team_update_request_form'),
     path('contact/', views.ContactFormView.as_view(), name='contact_form'),
     path('contact/result/', views.ContactResultView.as_view(), name='contact_result'),
     
     path('signup/', views.signup_view, name='signup'),
     path('signup_temporary_finish/', views.signup_temporary_finish_view, name='signup_temporary_done'),
     path('login/', views.login_view, name='login'),
     path('logout/', views.logout_view, name='logout'),
     path('user/<uuid:activate_token>/activation/', views.activate_user, name='activation_token'),
     path('user/<uuid:activate_token>/email_change/', views.change_email, name='email_change_token'),
     path('user/<slug:username>/player-comment/', views.UserProifilePlayerCommentDetail.as_view(template_name='user/user_comment_list/user_player_comment_list.html'), name='user_player_comment_list'),
     path('user/<slug:username>/manager-comment/', views.UserProifileManagerCommentDetail.as_view(template_name='user/user_comment_list/user_manager_comment_list.html'), name='user_manager_comment_list'),
     path('user/<slug:username>/club-team-comment/', views.UserProifileClubCommentDetail.as_view(template_name='user/user_comment_list/user_club_comment_list.html'), name='user_club_comment_list'),
     path('user/<slug:username>/nationa-team-comment/', views.UserProifileNationalCommentDetail.as_view(template_name='user/user_comment_list/user_national_comment_list.html'), name='user_national_comment_list'),
     path('user/<slug:username>/like-player-comment/', views.UserProifilePlayerLikeDetail.as_view(template_name='user/user_like_comment_list/user_like_player_comment_list.html'), name='user_like_player_comment_list'),
     path('user/<slug:username>/like-manager-comment/', views.UserProifileManagerLikeDetail.as_view(template_name='user/user_like_comment_list/user_like_manager_comment_list.html'), name='user_like_manager_comment_list'),
     path('user/<slug:username>/like-club-team-comment/', views.UserProifileClubLikeDetail.as_view(template_name='user/user_like_comment_list/user_like_club_comment_list.html'), name='user_like_club_comment_list'),
     path('user/<slug:username>/like-nationa-team-comment/', views.UserProifileNationalLikeDetail.as_view(template_name='user/user_like_comment_list/user_like_national_comment_list.html'), name='user_like_national_comment_list'),
     path('user/<slug:username>/follow-list/', views.FollowingListView.as_view(), name='following_list'),
     path('user/<slug:username>/follower-list/', views.FollowerListView.as_view(), name='follower_list'),
     path('user/<slug:username>/follow/', views.follow_view, name='follow'),
     path('user/<slug:username>/unfollow/', views.unfollow_view, name='unfollow'),
     path('user/settings/', views.UserSettingsView.as_view(), name='user_settings'),
     path('user/settings/password_change_form/', views.PasswordChangeView.as_view(template_name='user/password_change.html', success_url=reverse_lazy('soccer:password_change_done')), name='password_change_form'),
     path('user/settings/password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='user/password_change_finish.html'), name='password_change_done'),
     path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
     path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
     path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
     path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
     path('user/settings/username_change_form/', views.UserNameChangeView.as_view(template_name='user/username_change_form.html', success_url=reverse_lazy('soccer:username_change_done')), name="username_change_form"),
     path('user/settings/username_change_done/', views.UserNameChangeDoneView.as_view(template_name='user/username_change_finish.html'), name="username_change_done"),
     path('user/settings/nickname_change_form/', views.NickNameChangeView.as_view(template_name='user/nickname_change_form.html', success_url=reverse_lazy('soccer:nickname_change_done')), name="nickname_change_form"),
     path('user/settings/nickname_change_done/', views.NickNameChangeDoneView.as_view(template_name='user/nickname_change_finish.html'), name="nickname_change_done"),
     path('user/settings/email_change_form/', views.EmailChangeView.as_view(template_name='user/email_change_form.html', success_url=reverse_lazy('soccer:email_change_done')), name="email_change_form"),
     path('user/settings/email_change_done/', views.EmailChangeDoneView.as_view(template_name='user/email_change_finish.html'), name="email_change_done"),
     path('user/settings/user_icon_change_form/', views.UserIconChangeView.as_view(success_url=reverse_lazy('soccer:user_icon_change_done')), name="user_icon_change_form"),
     path('user/settings/user_icon_change_done/', views.UserIconChangeDoneView.as_view(), name="user_icon_change_done"),
     path('user/settings/profile_message_change_form/', views.ProfileMessageChangeView.as_view(success_url=reverse_lazy('soccer:profile_message_change_done')), name="profile_message_change_form"),
     path('user/settings/profile_message_change_done/', views.ProfileMessageDoneView.as_view(), name="profile_message_change_done"),
     path('user/settings/deactivate/', views.UserDeleteView.as_view(), name="user_deactivate"),
     path('user/settings/deactivate/confirm/', views.UserDeleteConfirmView.as_view(), name="user_deactivate_confirm"),
     path('user/delete/', views.user_delete_view, name="user_delete"),
     path('user/list/', views.UserListView.as_view(), name='user_list'),
     path('timeline/player-comment/', views.UserTimeLinePlayerCommentView.as_view(), name='user_timeline_player_comment'),
     path('timeline/manager-comment/', views.UserTimeLineManagerCommentView.as_view(), name='user_timeline_manager_comment'),
     path('timeline/club-comment/', views.UserTimeLineClubCommentView.as_view(), name='user_timeline_club_comment'),
     path('timeline/national-comment/', views.UserTimeLineNationalCommentView.as_view(), name='user_timeline_national_comment'),
     

     url(r'^getTeam/$', player_views.get_team),
     url(r'^getCountry/$', player_views.get_country),
]

