# Generated by Django 3.2.10 on 2023-04-23 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20230409_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerupdaterequest',
            name='birthday_day',
        ),
        migrations.RemoveField(
            model_name='managerupdaterequest',
            name='birthday_month',
        ),
        migrations.RemoveField(
            model_name='managerupdaterequest',
            name='birthday_year',
        ),
        migrations.RemoveField(
            model_name='playerupdaterequest',
            name='birthday_day',
        ),
        migrations.RemoveField(
            model_name='playerupdaterequest',
            name='birthday_month',
        ),
        migrations.RemoveField(
            model_name='playerupdaterequest',
            name='birthday_year',
        ),
        migrations.AddField(
            model_name='managerupdaterequest',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerupdaterequest',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
