# Generated by Django 3.2.10 on 2023-05-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0007_auto_20230503_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubupdaterequest',
            options={'ordering': ['name'], 'verbose_name_plural': '【更新リクエスト】チーム'},
        ),
        migrations.AlterModelOptions(
            name='nationalupdaterequest',
            options={'ordering': ['name'], 'verbose_name_plural': '【更新リクエスト】国籍'},
        ),
        migrations.CreateModel(
            name='PlayerNewCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('height', models.CharField(max_length=50)),
                ('foot', models.CharField(choices=[('右足', '右足'), ('左足', '左足')], max_length=50)),
                ('main_position', models.CharField(choices=[('GK', 'GK（ゴールキーパー）'), ('CB', 'CB（センターバック）'), ('LB', 'LB（レフトバック）'), ('RB', 'RB（ライトバック）'), ('DM', 'DM（ディフェンシブミットフィルダー）'), ('LWB', 'LWB（レフトウイングバック）'), ('RWB', 'RWB（ライトウイングバック）'), ('CM', 'CM（セントラルミットフィルダー）'), ('AM', 'AM（アタッキングミットフィルダー）'), ('LM', 'LM（レフトミットフィルダー）'), ('RM', 'RM（ライトミットフィルダー）'), ('SS', 'SS（セカンドストライカー）'), ('LW', 'LW（レフトウインガー）'), ('RW', 'RW（ライトウインガー）'), ('CF', 'CF（センターフォワード）')], max_length=100)),
                ('second_position', models.CharField(blank=True, choices=[('GK', 'GK（ゴールキーパー）'), ('CB', 'CB（センターバック）'), ('LB', 'LB（レフトバック）'), ('RB', 'RB（ライトバック）'), ('DM', 'DM（ディフェンシブミットフィルダー）'), ('LWB', 'LWB（レフトウイングバック）'), ('RWB', 'RWB（ライトウイングバック）'), ('CM', 'CM（セントラルミットフィルダー）'), ('AM', 'AM（アタッキングミットフィルダー）'), ('LM', 'LM（レフトミットフィルダー）'), ('RM', 'RM（ライトミットフィルダー）'), ('SS', 'SS（セカンドストライカー）'), ('LW', 'LW（レフトウインガー）'), ('RW', 'RW（ライトウインガー）'), ('CF', 'CF（センターフォワード）')], max_length=100, null=True)),
                ('third_position', models.CharField(blank=True, choices=[('GK', 'GK（ゴールキーパー）'), ('CB', 'CB（センターバック）'), ('LB', 'LB（レフトバック）'), ('RB', 'RB（ライトバック）'), ('DM', 'DM（ディフェンシブミットフィルダー）'), ('LWB', 'LWB（レフトウイングバック）'), ('RWB', 'RWB（ライトウイングバック）'), ('CM', 'CM（セントラルミットフィルダー）'), ('AM', 'AM（アタッキングミットフィルダー）'), ('LM', 'LM（レフトミットフィルダー）'), ('RM', 'RM（ライトミットフィルダー）'), ('SS', 'SS（セカンドストライカー）'), ('LW', 'LW（レフトウインガー）'), ('RW', 'RW（ライトウインガー）'), ('CF', 'CF（センターフォワード）')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.area')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.country')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.team')),
            ],
            options={
                'verbose_name_plural': '【新規追加リクエスト】選手',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NationalNewCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('association', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.area')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.manager')),
                ('manager_league_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.managerleaguearea')),
                ('manager_team_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.managerteamtype')),
            ],
            options={
                'verbose_name_plural': '【新規追加リクエスト】国籍',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagerNewCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.managerarea')),
                ('manager_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.managercountry')),
                ('manager_league_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.managerleaguearea')),
                ('manager_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.managerteam')),
                ('manager_team_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.managerteamtype')),
            ],
            options={
                'verbose_name_plural': '【新規追加リクエスト】監督',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubNewCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_established', models.CharField(max_length=100)),
                ('home_town', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.league')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.manager')),
                ('manager_league_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.managerleaguearea')),
                ('manager_team_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.managerteamtype')),
            ],
            options={
                'verbose_name_plural': '【新規追加リクエスト】チーム',
                'ordering': ['name'],
            },
        ),
    ]
