# Generated by Django 3.2.10 on 2023-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0008_auto_20230503_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='attack_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃力'),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='development_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='front_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='フロント'),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='manager_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='監督・コーチ'),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='achievement',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='実績'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='attack',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃戦術'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='defense',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備戦術'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='development',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='management',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='マネジメント'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AddField(
            model_name='managernewcreaterequest',
            name='political',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='政治力'),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='association_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='協会・連盟'),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='attack_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃力'),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='development_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='manager_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='監督・コーチ'),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='dribble_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ドリブル'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='pass_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='パス'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='physical_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='フィジカル'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='shoot_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='シュート'),
        ),
        migrations.AddField(
            model_name='playernewcreaterequest',
            name='speed_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='スピード'),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='author',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='text',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
