# Generated by Django 3.2.10 on 2023-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0011_auto_20230504_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_logo/'),
        ),
        migrations.AddField(
            model_name='clubnewcreaterequest',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='flag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nationalnewcreaterequest',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
