# Generated by Django 3.2.10 on 2023-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0013_auto_20230505_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubupdaterequest',
            name='year_established',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerupdaterequest',
            name='height',
            field=models.IntegerField(),
        ),
    ]
