# Generated by Django 3.2.10 on 2023-05-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0014_auto_20230505_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcommentlikeipaddress',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.team'),
        ),
        migrations.AddField(
            model_name='likeipaddress',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.player'),
        ),
        migrations.AddField(
            model_name='managerlikeipaddress',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.manager'),
        ),
        migrations.AddField(
            model_name='nationalcommentlikeipaddress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.country'),
        ),
    ]
