# Generated by Django 3.2.10 on 2023-05-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0015_auto_20230505_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcommentlikeipaddress',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.league'),
        ),
        migrations.AddField(
            model_name='nationalcommentlikeipaddress',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.area'),
        ),
    ]
