# Generated by Django 3.2.10 on 2023-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0016_auto_20230505_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcommentlikeipaddress',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='likeipaddress',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='managerlikeipaddress',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='nationalcommentlikeipaddress',
            name='comment_text',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
