# Generated by Django 3.2.10 on 2023-05-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0018_auto_20230506_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GK_Comment',
            new_name='GkComment',
        ),
    ]
