# Generated by Django 3.2.10 on 2023-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0019_rename_gk_comment_gkcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='handling',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ハンドリング'),
        ),
        migrations.AddField(
            model_name='comment',
            name='kick',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='キック'),
        ),
        migrations.AddField(
            model_name='comment',
            name='positioning',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ポジショニング'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reflexes',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='反射神経'),
        ),
        migrations.AddField(
            model_name='comment',
            name='saving',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='セービング'),
        ),
        migrations.DeleteModel(
            name='GkComment',
        ),
    ]
