# Generated by Django 3.2.10 on 2023-05-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0021_auto_20230506_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcomment',
            name='attack',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃力'),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='defense',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='development',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='front',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='フロント'),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='manager',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='監督・コーチ'),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='clubnewcreaterequest',
            name='attack_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃力'),
        ),
        migrations.AlterField(
            model_name='clubnewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AlterField(
            model_name='clubnewcreaterequest',
            name='development_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AlterField(
            model_name='clubnewcreaterequest',
            name='front_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='フロント'),
        ),
        migrations.AlterField(
            model_name='clubnewcreaterequest',
            name='manager_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='監督・コーチ'),
        ),
        migrations.AlterField(
            model_name='clubnewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='defense',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dribble',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ドリブル'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='handling',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ハンドリング'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='kick',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='キック'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pas',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='パス'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='physical',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='フィジカル'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='positioning',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ポジショニング'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reflexes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='反射神経'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='saving',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='セービング'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='shoot',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='シュート'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='speed',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='スピード'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='achievement',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='実績'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='attack',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃戦術'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='defense',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備戦術'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='development',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='management',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='マネジメント'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='ovr',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='political',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='政治力'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='achievement_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='実績'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='attack_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃戦術'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備戦術'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='development_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='management_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='マネジメント'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='political_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='政治力'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='association',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='協会・連盟'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='attack',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃力'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='defense',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='development',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='manager',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='監督・コーチ'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='nationalnewcreaterequest',
            name='association_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='協会・連盟'),
        ),
        migrations.AlterField(
            model_name='nationalnewcreaterequest',
            name='attack_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='攻撃力'),
        ),
        migrations.AlterField(
            model_name='nationalnewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AlterField(
            model_name='nationalnewcreaterequest',
            name='development_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='育成'),
        ),
        migrations.AlterField(
            model_name='nationalnewcreaterequest',
            name='manager_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='監督・コーチ'),
        ),
        migrations.AlterField(
            model_name='nationalnewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='defense_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='守備力'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='dribble_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='ドリブル'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='pass_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='パス'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='physical_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='フィジカル'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='shoot_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='シュート'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='speed_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '不明・評価しない'), (1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='スピード'),
        ),
    ]
