# Generated by Django 3.2.10 on 2023-05-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0022_auto_20230506_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeipaddress',
            name='like_click_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likeipaddress',
            name='like_flg',
            field=models.CharField(choices=[('0', '取り消し'), ('1', 'いいね済み')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubcomment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='ovr',
            field=models.PositiveSmallIntegerField(choices=[(1, ' 1（最悪）'), (2, ' 2（悪い）'), (3, ' 3（少し悪い）'), (4, ' 4（普通）'), (5, ' 5（やや良い）'), (6, ' 6（良い）'), (7, ' 7（最高）')], default=4, null=True, verbose_name='総合評価'),
        ),
    ]
