# Generated by Django 3.2.10 on 2023-05-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0023_auto_20230506_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcommentlikeipaddress',
            name='like_click_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubcommentlikeipaddress',
            name='like_flg',
            field=models.CharField(choices=[('0', '取り消し'), ('1', 'いいね済み')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='managerlikeipaddress',
            name='like_click_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managerlikeipaddress',
            name='like_flg',
            field=models.CharField(choices=[('0', '取り消し'), ('1', 'いいね済み')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='nationalcommentlikeipaddress',
            name='like_click_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalcommentlikeipaddress',
            name='like_flg',
            field=models.CharField(choices=[('0', '取り消し'), ('1', 'いいね済み')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubcommentlikeipaddress',
            name='comment_text',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='likeipaddress',
            name='comment_text',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='managerlikeipaddress',
            name='comment_text',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='nationalcommentlikeipaddress',
            name='comment_text',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
