# Generated by Django 3.2.10 on 2023-06-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0025_auto_20230611_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name_plural': '地域マスタ'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': '国籍マスタ'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'verbose_name_plural': 'リーグマスタ'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name_plural': 'チームマスタ'},
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.country'),
        ),
        migrations.AlterField(
            model_name='managernewcreaterequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.team'),
        ),
        migrations.AlterField(
            model_name='managerupdaterequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.country'),
        ),
        migrations.AlterField(
            model_name='managerupdaterequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.team'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.country'),
        ),
        migrations.AlterField(
            model_name='playernewcreaterequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.team'),
        ),
        migrations.AlterField(
            model_name='playerupdaterequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.country'),
        ),
        migrations.AlterField(
            model_name='playerupdaterequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.team'),
        ),
    ]
