# Generated by Django 3.2.10 on 2023-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0026_auto_20230618_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
