# Generated by Django 3.2.10 on 2023-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0027_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcomment',
            name='author',
            field=models.CharField(default='匿名', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='匿名', max_length=30),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='author',
            field=models.CharField(default='匿名', max_length=30),
        ),
        migrations.AlterField(
            model_name='nationalcomment',
            name='author',
            field=models.CharField(default='匿名', max_length=30),
        ),
    ]
