# Generated by Django 3.2.10 on 2023-08-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0029_blackip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackIp',
        ),
    ]
