# Generated by Django 3.2.10 on 2023-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0033_auto_20230828_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
