# Generated by Django 3.2.10 on 2023-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0037_auto_20230912_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='change_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
