# Generated by Django 3.2.10 on 2023-10-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0039_customuser_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_message',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
